db_connection_string: postgresql+asyncpg://postgres:123456@127.0.0.1:5432/packing_vietnam
host: 0.0.0.0
log_dir: logs
port: 8005
token_expiry_minutes: 1440

# MediaMTX servers configuration
mediamtx_servers:
  - ip: "10.72.216.112"
    port: 9997
    enabled: true
  - ip: "localhost"
    port: 9997
    enabled: true
  - ip: "127.0.0.1"
    port: 9997
    enabled: true
  - ip: "10.72.216.149"
    port: 9997
    enabled: true

# OAuth2:
oauth:
  secret_key: "AI2025"
  algorithm: "HS256"
  access_token_expire_minutes: 1440
  
  providers:
    internal:
      client_id: "iic-ai"
      client_secret: "Foxconn168!!"
      token_url: "https://10.220.7.195/oauth-service/oauth/token"
      user_info_url: "https://10.220.7.195/oauth-service/api/user/information"
      username_field: "profile"
      redirect_uri: "http://10.72.216.63:8005/v2/#/auth"
      logout_url: "https://fiisw-cns.myfiinet.com/oauth-service/logout"